### ISSUE TITLE
Arricchimento libft

### ISSUE THREAD

**Issue by dumbrosio** [dumbrosio/minishell#9]
https://github.com/dumbrosio/minishell/commit/5e4a8850796f178a867232c27878d001254ead4c#diff-965126adaab588c93f000ccca7595e786f2a7737e0e9c85d006ae3df6c091600

Dubbio scemo: siamo sicuri di poter modificare liberamente libft?

**Comment by almat101** [comment]
si, si puo fare. Per fare l'executor ho dovuto aggiungere ft_strcpy e ft_strcmp che mancano in libft. Per ora le ho messe dentro le utils di minishell. Se le vuoi lasciare la mettici pure ft_strncpy cosi non tocchiamo libft.

**Comment by dumbrosio** [comment]
se si può allora vanno bene in libft
